const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "aarav@example.com",
    password: "aarav",
    taskCounts: {
      accepted: 1,
      newTask: 1,
      completed: 2,
      failed: 2,
    },
    tasks: [
      {
        taskTitle: "Complete report",
        taskDescription: "Finish the quarterly financial report.",
        taskDate: "2024-10-20",
        category: "Finance",
        priority: "high",
        accepted: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Team meeting",
        taskDescription: "Attend the project team meeting.",
        taskDate: "2024-10-21",
        category: "Meetings",
        priority: "medium",
        accepted: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Code review",
        taskDescription: "Review the new module code.",
        taskDate: "2024-10-22",
        category: "Development",
        priority: "low",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Test the new feature",
        taskDescription: "Perform QA testing on the new feature.",
        taskDate: "2024-10-24",
        category: "Testing",
        priority: "high",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Update documentation",
        taskDescription: "Update the project documentation.",
        taskDate: "2024-10-25",
        category: "Documentation",
        priority: "medium",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Bug fixing",
        taskDescription: "Fix the critical bugs reported by QA.",
        taskDate: "2024-10-26",
        category: "Development",
        priority: "high",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 2,
    firstName: "Vivaan",
    email: "vivaan@example.com",
    password: "vivaan",
    taskCounts: {
      accepted: 2,
      newTask: 1,
      completed: 5,
      failed: 2,
    },
    tasks: [
      {
        taskTitle: "Design homepage",
        taskDescription: "Create a mockup for the homepage redesign.",
        taskDate: "2024-10-20",
        category: "Design",
        priority: "high",
        accepted: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Submit expenses",
        taskDescription: "Submit travel expenses for approval.",
        taskDate: "2024-10-19",
        category: "Finance",
        priority: "medium",
        accepted: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Client presentation",
        taskDescription: "Prepare slides for the client presentation.",
        taskDate: "2024-10-23",
        category: "Presentation",
        priority: "low",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Prepare marketing strategy",
        taskDescription: "Develop the marketing strategy for Q4.",
        taskDate: "2024-10-21",
        category: "Marketing",
        priority: "high",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Client follow-up",
        taskDescription: "Follow up with clients on project status.",
        taskDate: "2024-10-25",
        category: "Client Relations",
        priority: "medium",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Quality assurance check",
        taskDescription: "Perform QA check on completed tasks.",
        taskDate: "2024-10-24",
        category: "Quality Assurance",
        priority: "low",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 3,
    firstName: "Aditya",
    email: "aaditya@example.com",
    password: "aaditya",
    taskCounts: {
      accepted: 1,
      newTask: 2,
      completed: 6,
      failed: 2,
    },
    tasks: [
      {
        taskTitle: "Server migration",
        taskDescription: "Plan the migration of the production server.",
        taskDate: "2024-10-25",
        category: "IT",
        priority: "high",
        accepted: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Update software",
        taskDescription: "Update company software to the latest version.",
        taskDate: "2024-10-18",
        category: "Maintenance",
        priority: "medium",
        accepted: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Security audit",
        taskDescription: "Conduct a security audit of the internal systems.",
        taskDate: "2024-10-24",
        category: "Security",
        priority: "low",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Network monitoring",
        taskDescription: "Monitor network traffic for issues.",
        taskDate: "2024-10-23",
        category: "IT",
        priority: "high",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Data backup",
        taskDescription: "Perform data backup for the month.",
        taskDate: "2024-10-20",
        category: "IT",
        priority: "medium",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "System update",
        taskDescription: "Update all systems to the latest OS.",
        taskDate: "2024-10-26",
        category: "IT",
        priority: "low",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 4,
    firstName: "Karan",
    email: "karan@example.com",
    password: "karan",
    taskCounts: {
      accepted: 3,
      newTask: 1,
      completed: 10,
      failed: 2,
    },
    tasks: [
      {
        taskTitle: "Social media strategy",
        taskDescription: "Develop the Q4 social media strategy.",
        taskDate: "2024-10-22",
        category: "Marketing",
        priority: "high",
        accepted: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Market research",
        taskDescription: "Research competitors' recent campaigns.",
        taskDate: "2024-10-20",
        category: "Research",
        priority: "medium",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Post content",
        taskDescription:
          "Schedule the content for this week's social media posts.",
        taskDate: "2024-10-19",
        category: "Marketing",
        priority: "low",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Email campaign",
        taskDescription: "Launch the new email marketing campaign.",
        taskDate: "2024-10-21",
        category: "Marketing",
        priority: "high",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Feedback analysis",
        taskDescription: "Analyze feedback from previous campaigns.",
        taskDate: "2024-10-25",
        category: "Marketing",
        priority: "medium",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 5,
    firstName: "Riya",
    email: "riya@example.com",
    password: "riya",
    taskCounts: {
      accepted: 2,
      newTask: 3,
      completed: 3,
      failed: 5,
    },
    tasks: [
      {
        taskTitle: "Inventory check",
        taskDescription: "Verify the current inventory levels.",
        taskDate: "2024-10-17",
        category: "Operations",
        priority: "high",
        accepted: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Supplier follow-up",
        taskDescription:
          "Follow up with suppliers regarding the delayed shipments.",
        taskDate: "2024-10-18",
        category: "Logistics",
        priority: "medium",
        accepted: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Order processing",
        taskDescription: "Process the recent orders from the website.",
        taskDate: "2024-10-20",
        category: "Sales",
        priority: "low",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "System inventory audit",
        taskDescription: "Conduct an audit of the system inventory.",
        taskDate: "2024-10-22",
        category: "Operations",
        priority: "high",
        accepted: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Quality check",
        taskDescription: "Perform a quality check on the received shipments.",
        taskDate: "2024-10-24",
        category: "Quality Control",
        priority: "medium",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Shipping errors investigation",
        taskDescription: "Investigate the errors in recent shipping.",
        taskDate: "2024-10-26",
        category: "Logistics",
        priority: "low",
        accepted: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    firstName: "Akshay",
    email: "admin@example.com",
    password: "admin",
  }
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
